stages: 
  load_data:
    cmd: python src/load_data.py
    deps:
      - src/get_data.py
      - src/load_data.py
      - data_source:
          s3_source: data/raw/insurance.csv
    outs:
      - data/raws/insurance_cleaned.csv

  split_data:
    cmd: python src/split_data.py
    deps:
      - src/split_data.py
      - data/raws/insurance_cleaned.csv
    outs:
      - data/processed/train_insurance.csv
      - data/processed/test_insurance.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py
    deps:
      - src/train_and_evaluate.py
      - data/processed/train_insurance.csv
      - data/processed/test_insurance.csv
    outs:
      - models/model.pkl
      - reports/metrics.yaml
      - reports/parmas.yaml