base:
  project: mlops-insurance
  random_state: 20
  target_col: charges

data_source:
  s3_source: source_data/insurance.csv

load_data:
  raw_dataset_csv: data/raw/insurance_cleaned.csv

split_data:
  train_path: data/processed/train_insurance.csv
  test_path: data/processed/test_insurance.csv
  test_size: 0.2

estimator:
  ElasticNet:
    alpha: 0.5
    l1_ratio: 0.5

model_dirs: models

reports:
  params: reports/params.yaml
  metrics: reports/metrics.yaml


