base:
  project: mlops-insurance
  random_state: 20
  target_col: charges

data_source:
  s3_source: data/raw/insurance_cleaned.csv

load_data:
  raw_dataset_csv: data/raw/insurance_cleaned.csv

split_data:
  train_path: data/processed/train_insurance.csv
  test_path: data/processed/test_insurance.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.8
      l1_ration: 0.3

model_dirs: models

reports:
  params: reports/params.yaml
  score: reports/metrics.yaml

mlflow_config:
  artifact_dir: artifacts
  experiment_name: ElasticNet_Expenses
  run_name: mlops
  registered_model_name: ElasticNetMedicalExpenses
  remote_server_uri: http://localhost:5000


