# Generated by Django 4.1.10 on 2025-05-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (0, 'Female')])),
                ('bmi', models.FloatField()),
                ('children', models.FloatField()),
                ('smoker', models.IntegerField(choices=[(0, 'Smoker'), (1, 'non-Smoker')])),
                ('region', models.IntegerField(choices=[(3, 'Northwest'), (2, 'Northeast'), (1, 'Southwest'), (0, 'Southeast')])),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
    ]
