FROM node:22.11

# Set working directory
WORKDIR /frontend

# Copy only package.json and package-lock.json first
COPY ./frontend/package*.json ./

# Install dependencies first (cached if unchanged)
RUN npm install

# Now copy the rest of the frontend source code
COPY ./frontend .

# Clean up node_modules if needed (optional)
# RUN rm -rf node_modules && npm install  # only if rebuilding needed
EXPOSE 3000
EXPOSE 5173
# Run development server
CMD ["npm", "run", "dev"]
